stages:
  - test
  - deploy

variables:
  POSTGRES_PASSWORD: password
  POSTGRES_USER: user
  POSTGRES_DB: inventory

test:
  stage: test
  image: node:18
  services:
    - postgres:15.22
  script:
    - npm install
    - npm run format:check
    - npm run lint:quiet
    - npm run check
    - npm run test
  variables:
    DB_URL: postgres://user:password@postgres:5432/inventory

  except:
    - tags

deploy:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: ['']
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
      --destination "${CI_REGISTRY_IMAGE}:latest"

  only:
    - tags
