version: '3'
services:
  fastify-back-end_fastify-app_1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3003:3003'
    depends_on:
      - raap-postgresql
    env_file:
      - ./.env

  raap-postgresql:
    image: postgres:latest
    container_name: raap-postgresql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
