export default {
  'menu@users': 'with this permission you can see the user in menu',
  'user@user::tab':
    'with this permission you can see tab that show list of users',
  'user@user::create': 'with this permission you can add new user',
  'user@user::active': 'with this permission you can active/deactive user',
  'user@user::block': 'with this permission you can block/unblock user',
  'user@user::update': 'with this permission you can edit user',
  'user@user::delete': 'with this permission you can delete user',
  'user@user::list': 'with this permission you can get list of users',
  'user@user::myinfo': 'with this permission your info',
  'user@role::tab': 'with this permission you can see tab of roles',
  'user@role::create': 'with this permission you can add new role',
  'user@role::active': 'with this permission you can active/deactive a role',
  'user@role::update': 'with this permission you can edit role',
  'user@role::delete': 'with this permission you can delete role',
  'user@role::list': 'with this permission you can get list of roles',
  'user@inbound::list': '',
  'user@inbound::create': '',
  'configuration@unit::list': 'with this permission you can get list of units',
  'configuration@unit::create': 'with this permission you can add new unit',
  'configuration@unit::update': 'with this permission you can edit unit',
};
